name: Production Playwright Tests

permissions:
  contents: read
  actions: read

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"

jobs:
  run-e2e-tests:
    name: E2E Playwright Tests
    if: github.event.client_payload.environment === 'Production'
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install dependencies
        run: |
          pnpm install
          pnpm exec playwright install chromium

      - name: Run Playwright tests
        run: pnpm test
        env:
          PLAYWRIGHT_BASE_URL: ${{ github.event.client_payload.url }}
          PLAYWRIGHT_TEST_EMAIL: ${{ secrets.PLAYWRIGHT_TEST_EMAIL }}
          PLAYWRIGHT_TEST_PASSWORD: ${{ secrets.PLAYWRIGHT_TEST_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
